name: grade

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v4
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
  gatorgrader:
    runs-on: ubuntu-latest
    name: Run GatorGrader
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Run GatorGrader: see config/gatorgrader.yml
      - name: Run GatorGrader
        if: always()
        run:  |
          pip install gatorgrade
          gatorgrade --config config/gatorgrade.yml
